#!/bin/bash

nasm BootLoader.asm -f bin -o BOOT.BIN

nasm KernelEntryPoint.asm -f elf64 -o KernelEntryPoint.o

gcc  -c TheKernel.c -o TheKernel.o  -Wall

ld -o TheKernel.bin -Ttext 0x1000 KernelEntryPoint.o TheKernel.o --oformat binary

rm TheKernel.o
rm KernelEntryPoint.o

#cat BOOT.BIN kernel.bin BOOT.BIN > OS
cat BOOT.BIN TheKernel.bin BOOT.BIN > CU_FOS_OS

rm BOOT.BIN
rm TheKernel.bin

qemu-system-i386  CU_FOS_OS
 




