#!/bin/bash

nasm BootLoader.asm -f bin -o BootLoader.BIN

nasm KernelEntryPoint.asm -f elf64 -o KernelEntryPoint.o

gcc  -c TheKernel.c -o TheKernel.o  -Wall

ld -o TheKernel.bin -Ttext 0x1000 KernelEntryPoint.o TheKernel.o --oformat binary

rm TheKernel.o
rm KernelEntryPoint.o

 




