#!/bin/bash

nasm "Assembly/BootLoader.asm" -f bin -o "CU FOS OS/BootLoader.bin" 

nasm "Assembly/KernelEntryPoint.asm" -f elf64 -o "Assembly/KernelEntryPoint.o"

gcc  -c 'Kernel/TheKernel.c' -o 'Kernel/TheKernel.o'  -Wall

gcc  -c 'Hardware/Basic Drivers/VGA.c' -o 'Hardware/Basic Drivers/VGA.o'  -Wall

ld -o 'CU FOS OS/Kernel.bin' -Ttext 0x1000 'Assembly/KernelEntryPoint.o' 'Hardware/Basic Drivers/VGA.o' 'Kernel/TheKernel.o' --oformat binary

rm "Kernel/TheKernel.o"
rm "Assembly/KernelEntryPoint.o"
rm 'Hardware/Basic Drivers/VGA.o'

#cat BOOT.BIN kernel.bin BOOT.BIN > OS
cat "CU FOS OS/BootLoader.bin" "CU FOS OS/Kernel.bin"  > "CU FOS OS/OS Binary Image"



qemu-system-i386  "CU FOS OS/OS Binary Image"
 




